### ISSUE TITLE
TypeError: _globalThis.crypto.subtle is undefined

### ISSUE THREAD

**Issue by Eh1Ka6** [maxwellfortney/next-candy-machine#1]
![grafik](https://user-images.githubusercontent.com/3682446/137028055-de5a95ba-2598-4e24-9b26-e00d01c5af31.png)

Any idea where that could come from ?

**Comment by maxwellfortney** [comment]
Closing due to no update

**Comment by Eh1Ka6** [comment]
Figured out it's coming from an SSL problem if this one is not activated while testing the program
