### ISSUE TITLE
How to set maximum number of mint?

### ISSUE THREAD

**Issue by cdric** [maxwellfortney/next-candy-machine#17]
I'm getting from Phantom wallet:  "Unable to fetch balance changes" when trying to mint more than one token.

It seems to work for 1, or 2 tokens per mint but fails after that.

Does someone how I can debut this? 

Note: If I do click to approve the transaction is successful and I do get my NFT minted. It is just a bad user experience as the transaction cost isn't displayed on the phantom wallet UI

**Comment by maxwellfortney** [comment]
You can set the maximum number of mints in multiple ways. Using an input with a max={YOUR_DESIRED_MAX} is the easiest.

Multiple minting is not a feature supported by Candy Machine. All the mint instructions are added to a single transaction, and Phantom has difficulty understanding the total amount.

**Comment by cdric** [comment]
Oh thanks for letting me. I did try using Solflare and I can see all transactions post property along with each instruction. I'm gonna try to file a bug to the Phantom team to see if this can address that! In the meantime do you know who people would offer more than 2 mint to their customers if the transaction won't show the transaction price? Seems a no go for most people to approve a TX they can't see the cost associated with. What do you think?

**Comment by cdric** [comment]
Actually @maxwellfortney  do you happen to know if Phantom have a github repo where to post such request? Right know I'm filing a ticket through their website at: https://help.phantom.app/hc/en-us/requests/new
