### ISSUE TITLE
Documentation Update?

### ISSUE THREAD

**Issue by ck256-2000** [maxwellfortney/next-candy-machine#18]
Hi guys - 

great work - really loved the step by step guide.  heads and shoulders above what you normally see.

One question?  Do you need the following statement after Step 2?

solana config set --keypair ~/.config/solana/devnet.json

**Comment by maxwellfortney** [comment]
Its not 100% necessary because we specify the keypair location in every metaplex command, the only command that would need you to set the keypair in the config is `solana airdrop 1`, however you can also just do `solana airdrop 1 <YOUR_NEW_ADDRESS>`

**Comment by maxwellfortney** [comment]
Updated

**Comment by ck256-2000** [comment]
cool- thanks for the quick update.  congrats again on the very useful repo.
