### ISSUE TITLE
NOOB here - anyone know how to modify the CSS for the index.tsx 

### ISSUE THREAD

**Issue by ck256-2000** [maxwellfortney/next-candy-machine#22]
Been through the docs, tailwind site, etc and maybe I'm just missing it.

Anyone know how to modify the CSS styles?

looked at tsconfig etc etc

tia!

**Comment by maxwellfortney** [comment]
You can modify the styles by adding tailwind classes to the divs, in .tsx files

**Comment by maxwellfortney** [comment]
If you would like to commission me to make your website for you, i am available for hire

**Comment by ck256-2000** [comment]
interested - please dm at ***@***.***

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
