### ISSUE TITLE
Randomize mint

### ISSUE THREAD

**Issue by yoboitel** [maxwellfortney/next-candy-machine#26]
Hey, this project is awesome, is there anyway to randomize the mint ?
So if a user mint several nfts, he don't gets the following numbers nfts, like for example #112, #113, #114 but #34, #427, #298 ?

**Comment by maxwellfortney** [comment]
Randomize your assets before uploading to candy machine.

**Comment by yoboitel** [comment]
Hey, thank you, how can i do this ?
Directly in the hashlips art engine ? or after it's generated, but it needs to keep each pear of (image, json) ?
