### ISSUE TITLE
Unrecognized Custom SPL Token 

### ISSUE THREAD

**Issue by sudarshansb143** [maxwellfortney/next-candy-machine#27]
I have minted the custom SPL token.

It is all good  But On the solscan page my token is unrecognized 

See Here  

https://solscan.io/account/CXgusKwrUpDC51Wr3MJkayqox53Boyn12xa361mJRs99?cluster=devnet

![temp](https://user-images.githubusercontent.com/43947282/146002242-70e88b68-f7c5-458c-890a-9a09388edff5.PNG)

**Comment by maxwellfortney** [comment]
https://www.npmjs.com/package/@solana/spl-token-registry
