### ISSUE TITLE
Issue verifying uploads on mainnet beta 

### ISSUE THREAD

**Issue by TainedeBlaze** [maxwellfortney/next-candy-machine#28]
Hi, I recieve the following callstack when trying to verify my uploads,, not too sure where to go: 

PS C:\Users\Taine> ts-node metaplex/js/packages/cli/src/candy-machine-cli.ts verify -k .config/solana/devnet.json
wallet public key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(node:7896) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'program' of undefined
    at C:\Users\Taine\metaplex\js\packages\cli\src\candy-machine-cli.ts:212:54
    at step (C:\Users\Taine\metaplex\js\packages\cli\src\candy-machine-cli.ts:53:23)
    at Object.next (C:\Users\Taine\metaplex\js\packages\cli\src\candy-machine-cli.ts:34:53)
    at fulfilled (C:\Users\Taine\metaplex\js\packages\cli\src\candy-machine-cli.ts:25:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by maxwellfortney** [comment]
This is unrelated to this repo. You can find support for metaplex in their discord.
