### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by gw19191** [maxwellfortney/next-candy-machine#4]
Unhandled Runtime Error
Error: No router instance found.
You should only use "next/router" on the client side of your app.

Server Error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

**Comment by maxwellfortney** [comment]
I'm not able to replicate this. Have you added code to the base repo? There is no use of the next/router in the base code.

**Comment by gw19191** [comment]
I dont think ive added anything but let me try resetting it and see if that works. Thanks for the quick response!

**Comment by gw19191** [comment]
I pulled fresh and am still getting it. its coming from the next dependency. any ideas?

**Comment by maxwellfortney** [comment]
Yes, when running `yarn` for the first time I have the same warnings. Are you sure you are running `yarn dev` from the root of the repo?

![image](https://user-images.githubusercontent.com/29241388/137603812-c1d39864-13fe-483e-98f0-18462f0fdde6.png)

**Comment by gw19191** [comment]
yes I am. And still getting the same errors even after pulling fresh

**Comment by maxwellfortney** [comment]
Try deleting `.next` folder in the root of the project and re-run `yarn dev`

**Comment by maxwellfortney** [comment]
Are you on Windows?

**Comment by gw19191** [comment]
That was exactly it. wow what an extremely annoying bug! Thank you so much for the help!
